### PR TITLE
Backfill Nightscout

### PR DESCRIPTION
**Pull request by jpcunningh**
This is still in testing, but functionality has been verified through a couple of events now.

Lookout will query Nightscout for the most recent entry. If it is older than 6 minutes from current time, it will cycle through the stored history and upload any entry it finds that is later in time than the most recent Nightscout entry.

### CODE REVIEW

**Comment by jpcunningh** [comment]
Do you have an example set of data I could test for UTC?

**Comment by alimhassam** [comment]
How about just marking failed uploads when the publish to ns is being done and look at the error code? This would avoid the extra NS query.

**Comment by jpcunningh** [comment]
I checked both how moment handled both the UTC entries and the local tz entries in my Mongo db, and it handled them both correctly.

I modeled it after the OpenAPS method of back filling thinking that we could extend it to support multiple rigs running Lookout since that method works well for OpenAPS. I admit I haven't thought all the way through what would be needed.

If we have multiple rigs configured with Lookout, will only one be able to get a reading from the transmitter during reach read event even if more than one rig is in range, or will multiple rigs be able to obtain a reading and try to upload it? Would we need a mechanism to prevent multiple uploads of the same reading?

I can change to using the upload error code fairly easily if that method is better when considering how to provide a multiple rig capability.

Thoughts on how it would apply to multiple rigs?

Thanks!

**Comment by alimhassam** [comment]
I'm thinking this method would work better for multiple rigs. pseudo code would be something like this.

0. start with an empty entry-backfill cache.
1. read glucose entry(ies) (possibly requesting a dexcom backfill if we're missing last couple of entries locally)
2. try upload everything from entry-backfill cache + recently retrieved entries to NS.
2a. on sucess, clear entry-backfill cache
2b. on failure append recent entries to entry-backfill cache.
3. repeat from 1. in the next loop.

This would work better for multiple rig, because next time rigs come online they can re-try uploading the backfill entries. Without the dexcom backfill, ns would recieve all possible records. With dexcom backfill might receive some duplicate records, but i believe it already knows how to do de-duplication (to be confirm).

another reason this works better for multiple rigs, is that with the other method a new entry on ns from a second rig would disable entry backfill of pass unploaded record (on the first rig).

**Comment by jpcunningh** [comment]
I can confirm that NS can properly handle duplicate records.

However, a lot of people, including me, are using the free Heroku plan that has a MongoDB storage cap around 500 MB. I can only store around a month and a half of DeviceStatus data (230 MB) and 3 months of Entries data (40 MB), so I would not want to do anything to generate a potentially significant number of duplicates. I think that means we need to query NS to prevent uploading duplicates.

Has anybody run two or more rigs together to see how they interact with the transmitter? If the transmitter responds to two or more rigs simultaneously, preventing duplicates will be difficult because the rigs will query NS to identify missing entries at the same time.

After installing this branch on the rig this morning, I changed cron to use oref0-ns-loop (recalling the Feb @efidoman discussion in Gitter).

**Comment by jpcunningh** [comment]
Another thought towards the query method is that we would need to query the recent past to ensure the trend and noise calculations are accurate (at least until we implement the transmitter back fill).

I'm trying to run two rigs right now. The second rig is configured at woke up a couple of times, but hasn't been able to get a good read, yet. The primary rig is still going along with no missed readings.

**Comment by jpcunningh** [comment]
You are correct that the current logic doesn't handle that scenario. It would need to download the past X amount of time and back fill the readings it has that are missing. 

Does anybody have an opinion for how long we should make Lookout handle a back fill from being offline? 

I can go ahead and code that up over the next few days and incorporate it into this PR unless somebody would prefer to keep them separate.

**Comment by alimhassam** [comment]
the longest i've looped offline with xdrip-js-logger was for around 6h once, and it did the backfill great when i went back online.
is it too much to do 24h?

**Comment by jpcunningh** [comment]
I don't think 24h will be too much. It's only 24x12 = 288 potential readings to sort through. I'll change the local storage length to handle 24 hours and see if that causes any issues.

**Comment by efidoman** [comment]
I ran two rigs together both and only one of them can get the 5 minute update, so I don't believe there would be duplicates. Need to test further though.

**Comment by jpcunningh** [comment]
I observed the same behavior, but I haven't gone through the process of determining how long it would take for the transmitter to start talking to the second rig after connectivity is lost to first rig.

I have Lookout uploading calibration offset and slope to NS. I believe having Lookout sync glucose values and the latest calibration values with NS on a successful transmitter update or at the next multiple of 5 minutes from the last SGV readDate + 1 minute would provide a good multi-rig capability.

The multi-rig capability would be limited to mean that if the rig receiving updates from the transmitter goes down or out of range, the second rig would eventually take over receive updates. If it takes more than one update time period for the transmitter to transition to a new rig, it probably won't be useful to dispersing rigs throughout a house such that the user doesn't have to carry a rig on their person. However, if it takes 2 or 3 update time periods to transition, it probably will be useful for a backup rig running at night.

**Comment by jpcunningh** [comment]
@efidoman, @thebookins, @alimhassam, the code for this PR is fully implemented. I'm still testing, but if you can take a look at it and provide comments, I would appreciate it!

It was a fairly large code change that added the following functionality:
  * Inserts BG Check records in NS corresponding to the G5 official finger stick calibration events
  * Maintains an array of BG Check records and their corresponding unfiltered values for any BG Check
     event in NS since the most recent Sensor Start event in NS, synchronizing the data with NS
  * Maintains an array of the last 24 hours worth of glucose readings, synchronizing the data with NS
  * Maintains a calculated calibration obtained from least squares regression of officially calibrated
    glucose values and their corresponding unfiltered values, synchronizing it with NS
  * Handles transmitter id change events by restarting the worker thread with the new id
  * Restarts the worker thread after 6 minutes if it doesn't exit on its own

The sync runs every 5 minutes.

In addition to the items above, eslint "errors" were corrected and the asynchronous model was changed to use await and async.

Note that this requires Node 7.6.0 or later. I'm successfully running OpenAPS and Lookout with Node 8.9.4.

**Comment by jpcunningh** [comment]
I'm not sure how Lookout would have a significant impact on the battery life, and I don't have another point of reference to compare our battery life against. We have used Lookout since we started looping. We use a 2600 mAh 18650 battery that last us from morning into the evening, around 12-14 hours.  When I've had battery life issues, it was usually caused by a process using a lot of CPU resources.

When running Lookout, did you identify a process using a lot of CPU? I've looked at CPU usage from this branch.  It looks like a transmitter read event uses < 1 second of CPU and a sync event uses around 2 seconds. In contracts, the openaps nightscout loop uses 4-5 seconds of CPU.

I'm following the updates on xdrip-js-logger and plan to implement them in Lookout as time permits.

**Comment by efidoman** [comment]
:+1: 
Looking at the code now. One question, do you calculate the new LSR only when a new BG check / meter record is recorded or every loop?

**Comment by jpcunningh** [comment]
Resetting source for pull request to jpcunningh repository.

**Pull request closed without merging**
